# Generated by Django 2.0.5 on 2020-04-27 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MetadataDocument', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='document_file',
            field=models.FileField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='document',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='metadata',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False),
        ),
    ]
