# Generated by Django 2.0.5 on 2020-04-19 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MetadataDocument', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='id',
        ),
        migrations.RemoveField(
            model_name='metadata',
            name='id',
        ),
        migrations.AlterField(
            model_name='document',
            name='document_name',
            field=models.CharField(max_length=250, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='metadata',
            name='metadata_name',
            field=models.CharField(max_length=250, primary_key=True, serialize=False),
        ),
    ]
