# Generated by Django 2.0.5 on 2020-04-19 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MetadataDocument', '0003_auto_20200419_2028'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='document_file',
            field=models.FileField(blank=True, upload_to='document'),
        ),
    ]
