# Generated by Django 2.0.5 on 2020-04-26 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MetadataDocument', '0006_auto_20200420_0944'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='metadata',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
