# Generated by Django 2.0.5 on 2020-04-26 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MetadataDocument', '0007_auto_20200427_0202'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='id',
            field=models.BigIntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='metadata',
            name='id',
            field=models.BigIntegerField(primary_key=True, serialize=False),
        ),
    ]
